### PR TITLE
Initial update for website landing page

### PR DESCRIPTION
**Pull request by chenette**
This PR replace the previous landing page content with text that's more appropriate for a general (non-developer) audience.
    
This commit also adds a Splinter logo to the /assets directory so that it's available if desired. (It was used in a previous draft of this PR.)

**View the changes at** https://grid-test.sawtooth.me/ 

**Test locally:**

1. Run this in the root directory: `just run`

2. Wait until you see `grid-docs-jekyll       |   Server running... press ctrl-c to stop.`

3. Point your browser to `0.0.0.0:8080`

Signed-off-by: Anne Chenette <chenette@bitwise.io>

### CODE REVIEW

**Comment by davececchi** [comment]
Brain dump:

-----

Hyperledger Grid is a framework for building distributed supply chain solutions.

Grid provides implementations of open, standards-based business processes and 
data concepts that immediately align your trading relationships and accelerate 
your shared time to value.


Why Grid is Good
- Pre-built content
- Flexible deployment models
- Open and free

Explore the Capabilities
- Product Data / Catalog
- Product Inventory
- Purchasing

Getting Started With Grid
- Run a demo on Splinter

Getting Involved
- Community stuff

**Comment by chenette** [comment]
Thanks, @davececchi , for the very helpful brain dump!  I've force-pushed a new draft of the Grid landing page and would be very grateful for your feedback.

**Comment by chenette** [comment]
You can view the landing page changes at: https://grid-test.sawtooth.me/

**Comment by chenette** [comment]
Closing this PR because more work is needed to agree on the right content for this first update.

**Pull request closed without merging**
